def freqPattern(string, k):
    length_str = len(string)
    count = []
    freq_pat = []

    for i in range(length_str-k):
        string_pat = string[i:i+k]
        count.append(findPattern(string, string_pat))

    maxCount = max(count)

    for x in range(length_str-k):
        if count[x] == maxCount:
            freq_pat.append(string[x:x+k])

    set(freq_pat)

    return freq_pat            

def findPattern(string, pattern):
    length_str = len(string)
    length_pat = len(pattern)
    count = 0
    for i in range(length_str-length_pat):
        string_pat = string[i:i+length_pat]
        if string_pat == pattern:
            count += 1
    return count

print freqPattern("GTAATGACGGTGAGTGCGGATATCATTATCTACAATGTCGGATATCATTATCTATTATCTGTAATGACATTATCTATTATCTACAATGTGGTGAGTGCGGATATCGGTGAGTGATTATCTACAATGTGGTGAGTGATTATCTGTAATGACGGTGAGTGGGTGAGTGACAATGTATTATCTACAATGTGGTGAGTGACAATGTACAATGTGTAATGACGTAATGACACAATGTCGGATATCATTATCTATTATCTGTAATGACATTATCTATTATCTATTATCTGTAATGACACAATGTGGTGAGTGATTATCTGTAATGACATTATCTGGTGAGTGACAATGTGTAATGACCGGATATCCGGATATCATTATCTACAATGTGGTGAGTGGTAATGACGGTGAGTGGGTGAGTGACAATGTGGTGAGTGGTAATGACGTAATGACGTAATGACATTATCTCGGATATCACAATGTACAATGTCGGATATCGGTGAGTGGGTGAGTGGGTGAGTGGTAATGACATTATCTGTAATGACATTATCTATTATCTGTAATGACGTAATGACGTAATGACGTAATGACATTATCTATTATCTGGTGAGTGGGTGAGTGGTAATGACATTATCTATTATCTGGTGAGTGACAATGTGTAATGACACAATGTCGGATATCCGGATATCGGTGAGTGACAATGTACAATGTGGTGAGTGACAATGTCGGATATCATTATCTGGTGAGTGGGTGAGTGCGGATATCCGGATATCCGGATATCGTAATGACGGTGAGTGATTATCTACAATGTGTAATGACATTATCTGGTGAGTGATTATCTGTAATGACCGGATATCGTAATGACGTAATGACATTATCT", 12)
