from fileReader import fileReader

def DeBruijn(string,k):
    stringList = []
    adjList = {}

    for i in range(len(string)-k+1):
        stringList.append(Prefix(string[i:i+k]))
        if i == range(len(string)-k+1)[-1]:
            stringList.append(Suffix(string[i:i+k]))

    for string in stringList:
        indexList = [idx for idx, item in enumerate(stringList) if item == string]
        adjList[string] = []
        for idx in indexList:
            if idx < len(stringList)-1:
                adjList[string].append(stringList[idx+1])

        if adjList[string] == []:
            adjList.pop(string)
    
    return adjList

def Prefix(string):
    return string[:-1]

def Suffix(string):
    return string [1:]

stringList = fileReader()

adjList = DeBruijn("TAGTACCAAGGAACAGTGCCAAAGGGAACGCAATAGCGCTGTGGACATAAGGGGGCAATCGAACCAAAAGGGGGGCAGGCGGCGCGCATTACTTGAACTTATACCAAGGATTGGAAAGCTCGCAACATGAATCATCTCACCAGCACTACGCGTGTGCCGGTGTCTGTTGACTGTGGACTACCAGCTAAGGGCGGGGTTCGTACGGACCGCTAGCGGCTGTCCGCGCATAATGGGAAGAAAAATTGGTCCGTAGGGTATGAGAGTCGGAAACACCAACATCCCGCATGTGGGCTTAGACGCATCGATATTGGTGACCACGTGAGTCAGGCCCTCACCTGCCTTGGTCGTAGCGCTCGGACACTACGAGTCAGCGTTCTCCGATGGCAAATCATAAGTTGCGGGGTCGATTTTACCATGCGTTACGCAACAGTTGGGGATAGAGGTGGTCCTGTAGTCAAGTACACTTACTTTATTCATACGTGATGCAACATCTCCGAGCTCATGAGTGATTGTTGAACCGGAGTGCGGTTTAGGCATCGTTTAGCAGATGTCACTCCTATTCCGTGACTGGTTTGTGTGACATTCGACATCCAGTGAGTCGCGACGACACAGGCGGCGTCCCAACGATGCCCTTTGATTGCGCAGATAGTTCATACACCTCCCCTTTCATGCTTTCAATACGTATTGCGTGTGAGTCATAGCACACGGGATCGAAGAAACCCTACAAGTTGGCACCGTCAAGGTCTCAACTTCTCTGCGCCCATTAGCTCATTGGTGTGACCTGCACGGGAATCGACTATCCGACATAAGACCAGCTGGGATTGGACCGAGCCCCGTGGTGTCACGTAAATGCGTGGTTGTTGTCAGCAGAACTACTTGGCCTTCTTACGACTGTAGCACACACCTTAGCCACGGTGTACTGATGATTTACAAGTAATCGAAGAAGGTTTCTTCGTTCCCACTCTTGCTGTACAAGCATCTTTCGTAGGGACTAAAACCGAGTATCCGGTTGATTTCAACAGGAGGTTGTATAGCTCCGTGTTATTGGCTTAGCCTTGGCCTAACTTTGTGGTTCACATACTACCATGAATGGGGAGGTATTAGCGAATACCCGCAGGACGGAGATAAGCGTGCCGCGTTCCCGCCCCTTCGGTGCCCGGTAGTTTATACGATCTAGCTCGACAGCGGATCTGGTCTTATACGATTGTCTTCGGTCCGAAACAGATAGTCTTTCTAGTGACCGACGAGAATTCTAGCCAATCTACCGTTTCGTGGCGTCCCGCTTGCGACATTTAAGTGCCCGTTATAGGACGATAAGCATTTGCGGGACGTGGAATCGTAGATGCTTTATTGTACGCCATATGGGTGGCGGCTGGGTTTCGGTCGCACCTAATTAAGGCGTGCTAGTCATGGGCTGGCCGGTTGCGCATGCGCTCGGGCGTACTAGCCTACCTGTCGAGAAGAGTTCTCTGGTGACGAGTCAGGTCCATGGTTCCTCTTTTTGACGCGTGCAAAGATAATCATTGAAAGACGCCCTAGACCGCTTCCTCTCAACGGCGTTCCAATCAAGAAGGTCCACAGTGGATTTAGGCACTCATTTGTATGCCTAGAGGCACTTTACCAGGTGGATCGGCAAACAAATAATCTACAGTACTACAGCCAGAAGTTGTCTGGTTGTGCGTCAAATCTAATCAACCGGCGAAGGGTCAGACCACACGGCGATTATCACAATCTCGACATGGAGTTCGGTAAATCGTAAGCGAGATCCTATTATTATCGGTATGCAGGTTTCTGTCCCCTTTGAGACGCTCTGAGACCTTCAAGTGCGCGGTTGCCCAAAGCGGTTGTGCTCACTTTAAGGATCTGGTCTCCACAATCCTGATGTCTCGCCACACTGATCGGAAAAAGCTATGGGCGGAAGTGGTGCAAGGGATCTCTGTTTACACATTGGCCTGAATATTCCCACAAGAATTATAGCCATACGAAATAAGCTCTTCAGC",12)

for item in adjList:
    print item + " -> " + ",".join(adjList[item])

